# This file is part of the YesWiki Extension nextcloudconnector.
# Authors : see README.md file that was distributed with this source code.
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.
parameters:
  # parameters to connect to nextcloud instance
  nextcloudconnector:
    servername: ''
    username: ''
    applicationPassword: ''
  # for edit config action
  nextcloudconnector_editable_config_params:
    - nextcloudconnector:
      - servername
      - username
      - applicationPassword

services:
  _defaults:
    autowire: true
    public: true

  YesWiki\Nextcloudconnector\Service\:
    resource: 'services/*'